include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_left_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_right_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
