include:
  - board: xiao_ble
    shield: ergonaut_one_left rgbled_adapter
    artifact-name: ergonaut_one_left
  - board: xiao_ble
    shield: ergonaut_one_right rgbled_adapter
    artifact-name: ergonaut_one_right
  - board: xiao_ble
    shield: settings_reset
