include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
